"""add_pattern_and_rate_to_incident

Revision ID: 0a865dfc32fe
Revises: 3c77a1ee9a97
Create Date: 2026-03-23 19:39:40.316003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a865dfc32fe'
down_revision: Union[str, None] = '3c77a1ee9a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('error_pattern', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('error_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'error_rate_pct')
    op.drop_column('incidents', 'error_pattern')
    # ### end Alembic commands ###
